language: node_js
node_js:
- 10
install:
- npm install
- npm install -g codecov
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: brajevicms@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: 'true'
