language: node_js
node_js:
  - 14
os: linux
dist: xenial
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
before_deploy: 'npm run build'
deploy:
  provider: npm
  email: brajevicms@gmail.com
  api_token: $NPM_API_KEY
  on:
    repo: brajevicm/next-universal-route
    branch: master
  cleanup: true
