language: node_js
node_js:
  - 14
os: linux
dist: xenial
install:
  - npm install -g npm@7.22.0
  - npm install -g codecov
  - npm install
cache:
  directories:
    - node_modules
before_deploy: 'npm run build'
deploy:
  provider: npm
  email: brajevicms@gmail.com
  api_token: $NPM_API_KEY
  on:
    repo: brajevicm/next-universal-route
    branch: master
  skip_cleanup: true
