language: node_js
node_js:
  - 10
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
before_deploy: 'npm run build'
deploy:
  provider: npm
  email: brajevicms@gmail.com
  api_key: $NPM_API_KEY
  on:
    repo: brajevicm/next-universal-route
    branch: master
  skip_cleanup: 'true'
